### ISSUE TITLE
Select a Recipe: As the event Host, I want to select a recipe and see a description of that meal presented before the final decision, after which it can be added to the corresponding event.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#10]
Acceptance Criteria:
- [x] Display detailed recipe information (ingredients, instructions).
- [x] Associate selected recipe with the event.
- [x] Allow multiple recipes per event.

**Development Tasks:**
- [x] sopra-fs24-group-10/Client#12
- [x] sopra-fs24-group-10/Server#36
- [x] sopra-fs24-group-10/Client#13
- [x] sopra-fs24-group-10/Server#38
- [x] sopra-fs24-group-10/Client#14

**Comment by noystad** [comment]
**Development Tasks:**
- [ ] Implement UI for selecting a recipe.
- [ ] Create backend logic to retrieve detailed recipe information (ingredients, instructions).
- [ ] Display detailed recipe information before final decision.
- [ ] Implement functionality to associate the selected recipe with the event.
- [ ] Allow multiple recipes to be selected and associated with the event.

**Comment by mikfre1** [comment]
a3bba9eea49b6fbd4cd9e2d5f448f51aa7a6dda2
