### ISSUE TITLE
Ingredient Assignment Table: As a group member, I want to see a clear overview showing which ingredients I'm responsible for bringing to the event and others as well.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#13]
Acceptance Criteria:
- [ ] Overview lists each ingredient and assigned person.
- [ ] Easy updating of assignments.
- [ ] Highlight any remaining unassigned ingredients.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Server#54
- [ ] sopra-fs24-group-10/Client#24
- [ ] sopra-fs24-group-10/Client#25
- [ ] sopra-fs24-group-10/Client#26

**Comment by mikfre1** [comment]
8fcf0e753ad90f4c16c89d5b567a803d9eb0420e
