### ISSUE TITLE
Save and View Recipe Favorites: As a logged-in user, I want to save my favourite recipes to a list so I can easily access them in my profile page.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#14]
Acceptance Criteria:
- [ ] Add recipes to "favourites" with a single click.
- [ ] Dedicated "favourites" section in profile.
- [ ] Access favourites in user profile.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Client#29
- [ ] sopra-fs24-group-10/Client#27
- [ ] sopra-fs24-group-10/Client#28
- [ ] sopra-fs24-group-10/Server#61

**Comment by mikfre1** [comment]
8fcf0e753ad90f4c16c89d5b567a803d9eb0420e
