### ISSUE TITLE
Collaborative Note Board: As a group member, I want to have a shared note board for our event where we can jot down ideas, modifications, or reminders related to the recipe to ensure everyone is on the same page.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#15]
Acceptance Criteria:
- [ ] Dedicated note board within each event.
- [ ] All group members can add and edit notes.
- [ ] Real-time saving and visibility for the entire group.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Client#30
- [ ] sopra-fs24-group-10/Server#63
- [ ] sopra-fs24-group-10/Client#31
- [ ] sopra-fs24-group-10/Server#65
