### ISSUE TITLE
Recipe Rating: As a user, I want to rate recipes, so that we can build a library of tried-and-loved options.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#16]
Acceptance Criteria:
- [ ] Provide star rating for recipes after event.
- [ ] Display average rating for recipes.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Client#32
- [ ] sopra-fs24-group-10/Server#67
- [ ] sopra-fs24-group-10/Client#33
- [x] #91
- [x] #92
