### ISSUE TITLE
User Login: As a registered user, I want to log in to the web app with my username and password so that I can access my personalized features.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#5]
Acceptance Criteria:
- [x] Redirect to Event Overview page after valid login.
- [x] Display error message for incorrect username or password.
- [x] Provide option to change forgotten password.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Client#4
- [ ] sopra-fs24-group-10/Server#24
- [ ] sopra-fs24-group-10/Client#5
- [ ] sopra-fs24-group-10/Client#6

**Comment by noystad** [comment]
**Development Tasks:**
- [ ] Implement login form with fields for username and password.
- [ ] Create backend logic to authenticate user credentials.
- [ ] Redirect to Event Overview page upon successful login.
- [ ] Display error message if username or password is incorrect.
