### ISSUE TITLE
Edit User Profile: As a logged-in user, I want to edit my profile settings (username, password) so that I can change my preferences.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#6]
Acceptance Criteria:
- [ ] Access and edit profile information.
- [ ] Save changes in real-time.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Client#15
- [ ] sopra-fs24-group-10/Server#41
- [ ] sopra-fs24-group-10/Server#42
