### ISSUE TITLE
Invite Group Members: As a logged-in event Host, I want to invite friends to a dinner group by entering their username so that we can collaborate on event planning.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#7]
Acceptance Criteria:
- [x] Create a group belonging to the event.
- [x] Add multiple usernames to invitation list.
- [x] See acceptance/decline status within the group.

**Development Tasks:**
- [ ] sopra-fs24-group-10/Client#7
- [ ] sopra-fs24-group-10/Server#28
- [ ] sopra-fs24-group-10/Client#8

**Comment by noystad** [comment]
**Development Tasks:**
- [ ] Implement UI for inviting friends to a dinner group.
- [ ] Create backend logic to handle group creation for the event.
- [ ] Allow the event host to add multiple usernames to the invitation list.
