### ISSUE TITLE
As a user, I want to switch between dark and light mode themes so that I can personalize my experience and reduce eye strain in low-light environments.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Server#76]
Acceptance Criteria:

- A clearly visible toggle exists to switch between dark mode and light mode.
- The theme change persists across sessions.
- The chosen theme provides sufficient contrast for usability in all lighting conditions.

Development Tasks:

- [x] sopra-fs24-group-10/Client#46
- [x] sopra-fs24-group-10/Client#47
- [x] sopra-fs24-group-10/Client#48
- [x] sopra-fs24-group-10/Server#80
- [x] #81

**Comment by Modemacher** [comment]
Somehow it did not work to close the Issue with the terminal in Intelij

**Comment by Modemacher** [comment]
a42bcb163f7d1ca1808ee5e6ba728363876a1ca1

**Comment by Modemacher** [comment]
05546ded6c8c39e5c26dd68740cf445b8634336a

**Comment by Modemacher** [comment]
?

**Comment by Modemacher** [comment]
054505b00c76e51593f5b1b7cf22dda092739109

**Comment by Modemacher** [comment]
Something is off with the Commit Numbers I don't know what it is.
