### ISSUE TITLE
As a user, I want to upload a profile picture so that I can personalize my account and be recognizable to other users.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Server#85]
Acceptance Criteria:

- An option in the profile settings allows users to upload an image.
- Common image formats (JPEG, PNG) are supported.
- The uploaded image displays correctly on the profile page.

Development Tasks:

- [ ] sopra-fs24-group-10/Client#50
- [ ] sopra-fs24-group-10/Server#87
- [ ] sopra-fs24-group-10/Server#88
- [ ] sopra-fs24-group-10/Client#51
