### ISSUE TITLE
Manage Multiple Events: As a user, I want to view a list of all the events I'm part of (past, current, and upcoming) so I can keep track of my dinner commitments.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Server#9]
Acceptance Criteria:
- [ ] Events listed chronologically with clear dates and titles.
- [ ] Easy distinction between past, current, and future events.
- [ ] Click event to view full details.

**Development Tasks**
- [ ] sopra-fs24-group-10/Server#43
- [ ] sopra-fs24-group-10/Client#16
- [ ] sopra-fs24-group-10/Client#17
- [ ] sopra-fs24-group-10/Client#18
