### ISSUE TITLE
As a logged-in user, I want to delete my user profile so that all my personal information is removed from the system.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Server#94]
Acceptance Criteria:
- [ ] I can easily locate the option to delete my user profile within my account settings.
- [ ] The system clearly warns me of the permanent consequences of deleting my profile.

Developer Tasks:
- [ ] sopra-fs24-group-10/Client#52
- [ ] sopra-fs24-group-10/Client#53
- [ ] sopra-fs24-group-10/Server#97
- [ ] sopra-fs24-group-10/Server#98
