### ISSUE TITLE
 As an event participant, I want to remove myself from the event so that I am no longer listed as a participant.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Server#99]
Acceptance Criteria:

- [ ] I can easily find the option to remove myself from an event.
- [ ] The system asks me to confirm my decision to leave the event.
- [ ] I am no longer listed as a participant on the event page.

Developer Tasks: 
- [ ] sopra-fs24-group-10/Client#54
- [ ] sopra-fs24-group-10/Client#55
- [ ] sopra-fs24-group-10/Server#102
- [ ] sopra-fs24-group-10/Server#103

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/c1db7b7316efe882e3e7e0607b8b0cf579a3f01e
